// client/src/pages/RegisterPage.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { TextField, Button, Typography, Container, Box, Paper, Link } from '@mui/material';
import type { User } from '../types/interfaces';

const RegisterPage: React.FC = () => {
  const [formData, setFormData] = useState<User>({
    fname: '',
    lname: '',
    email: '',
    dob: '', // Placeholder, ideally a date picker
    password: '',
    phone: '',
    timezone: 'UTC', // Default or fetched
    role: 'user', // Default role
    id: '', // Will be generated by backend
    daily_send_limit: 0, // Default or handled by backend
    created_at: '',
    lastLogin: '',
    created_by: '',
    is_active: true,
    is_verified: false,
    verified_at: '',
  });
  const [error, setError] = useState('');
  const { register } = useAuth();
  const navigate = useNavigate();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setError('');
    try {
      // Basic validation - password should not be empty
      if (!formData.password) {
        setError('Password cannot be empty.');
        return;
      }
      // The backend handles UUID, dates, etc. for now, only send what's required by the DTO.
      // The User interface expects many fields, but the register API likely only needs a subset.
      // For this prototype, I'm sending the full formData.
      await register(formData);
      navigate('/');
    } catch (err) {
      setError('Registration failed. Please try again.');
      console.error(err);
    }
  };

  return (
    <Container component="main" maxWidth="xs">
      <Box
        sx={{
          marginTop: 8,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        <Paper elevation={6} sx={{ p: 4, borderRadius: 2 }}>
          <Typography component="h1" variant="h5" sx={{ mb: 2 }}>
            Sign Up for MyMail
          </Typography>
          <Box component="form" onSubmit={handleSubmit} noValidate sx={{ mt: 1 }}>
            <TextField
              margin="normal"
              required
              fullWidth
              id="fname"
              label="First Name"
              name="fname"
              autoComplete="given-name"
              value={formData.fname}
              onChange={handleChange}
            />
            <TextField
              margin="normal"
              required
              fullWidth
              id="lname"
              label="Last Name"
              name="lname"
              autoComplete="family-name"
              value={formData.lname}
              onChange={handleChange}
            />
            <TextField
              margin="normal"
              required
              fullWidth
              id="email"
              label="Email Address"
              name="email"
              autoComplete="email"
              value={formData.email}
              onChange={handleChange}
            />
            <TextField
              margin="normal"
              required
              fullWidth
              name="password"
              label="Password"
              type="password"
              id="password"
              autoComplete="new-password"
              value={formData.password}
              onChange={handleChange}
            />
             <TextField
              margin="normal"
              fullWidth
              id="phone"
              label="Phone Number"
              name="phone"
              autoComplete="tel"
              value={formData.phone}
              onChange={handleChange}
            />
             <TextField
              margin="normal"
              fullWidth
              id="dob"
              label="Date of Birth (YYYY-MM-DD)"
              name="dob"
              value={formData.dob}
              onChange={handleChange}
            />
            {error && (
              <Typography color="error" variant="body2" sx={{ mt: 1 }}>
                {error}
              </Typography>
            )}
            <Button
              type="submit"
              fullWidth
              variant="contained"
              sx={{ mt: 3, mb: 2 }}
            >
              Sign Up
            </Button>
            <Link href="/login" variant="body2">
              {"Already have an account? Sign In"}
            </Link>
          </Box>
        </Paper>
      </Box>
    </Container>
  );
};

export default RegisterPage;
